### ISSUE TITLE
Impl expansion incorrectly adding lifetime from method

### ISSUE THREAD

**Issue by MrJerB** [audunhalland/entrait#29]
Hi there, 

Thanks for the library as well as the concept! I might have discovered a case of incorrect expansion in a certain scenario. I'll try to explain below:

I have a handwritten trait named `Foo` in crate A which I then want to implement as `MyFoo` in crate B.
The expansion in crate B is causing errors due to the lifetime specified in the method I prescribed in my handwritten trait.

The `DoFoo` method in my trait contains a lifetime parameter (my real implementation involves tokenizing some input string, and preferably I would like to avoid clones).

<details>
<summary>Crate A (no issues)</summary>

## Crate A:

```rust
#[entrait(FooImpl, delegate_by = FooDelegate)]
trait Foo {
    fn DoFoo<'a>(&self, input: &'a str) -> &'a str;
}
```

## Crate A expanded (no issues):

```rust
trait Foo {
    fn DoFoo<'a>(&self, input: &'a str) -> &'a str;
}

trait FooImpl<EntraitT>: 'static {
    fn DoFoo<'a>(__impl: &::entrait::Impl<EntraitT>, input: &'a str) -> &'a str;
}
pub trait FooDelegate<T> {
    type Target: FooImpl<T>;
}

impl<EntraitT: Sync> Foo for ::entrait::Impl<EntraitT>
where
    EntraitT: FooDelegate<EntraitT> + Sync + 'static,
{
    #[inline]
    fn DoFoo<'a>(&self, input: &'a str) -> &'a str {
        <EntraitT::Target as FooImpl<EntraitT>>::DoFoo(self, input)
    }
}
```
</details>

<details>
<summary>Crate B</summary>

## Crate B

```rust
struct MyFoo;

#[entrait]
impl FooImpl for MyFoo {
    fn DoFoo<'a, D>(deps: &D, input: &'a str) -> &'a str {
        input
    }
}
```

## Crate B expanded (issue is here)

```rust
impl MyFoo {
    fn DoFoo<'a, D>(deps: &D, input: &'a str) -> &'a str {
        input
    }
}

// Issue lies here: as the lifetime is added to the impl for the trait and in the wrong order (it is not needed at all)
impl<EntraitT: Sync, 'a> FooImpl<EntraitT, 'a> for MyFoo {
    #[inline]
    fn DoFoo<'a>(__impl: &::entrait::Impl<EntraitT>, input: &'a str) -> &'a str {
        Self::DoFoo(__impl, input)
    }
}
```

</details>

I am using version `0.5.3` of the crate.

**Comment by audunhalland** [comment]
Hi, thanks for your interest and for reporting an issue! I'll try to look into it.

Entrait is not something I engage with every day. Whether it's really a viable design pattern for production code is for me an open question, and the answer to that is dependent on people evaluating it, so thanks :) 

This (on first glance) seems like a proper bug.

PS: PRs are very welcome!

**Comment by audunhalland** [comment]
`0.6.0` released. The reason for the major bump is that unimock was already bumped some time ago on the main branch. I initially planned some other changes before 0.6.0 but I never got to do them.
